### ISSUE TITLE
[Enhancement] Sqlite Virtual Tables / Custom Functions

### ISSUE THREAD

**Issue by 65001** [litdev1/LitDev#12]
Is there anyway to add Virtual Tables or Custom Functions to LDDatabase? IE would it possible to make a method or function along the lines of 
```
LDDatabase.AddSqliteFunction(Primitive Database,Primtive Function Name , Primitive Type, Primitive Arguments)
{
//Code
}

LDDatabase.AddVirtualTable(Primitive Database,Primitive Module Name,Primitive arguments)
{
//Code
}
```

**Comment by litdev1** [comment]
I expect this could be done.  I don't have any experience using virtual tables or custom functions.

First I would understand more about what they would be used for and decide on a simple test use.  Then test in C# ouside SB - the syntax and requirement for callback functions and inserting functions by reflection looks tricky, so maybe try to find a sample to start from on the web.

Only then work out what an implementation in SB would look like - you may already have done much of the first bits, otherwise googling does show some samples and ideas on this topic.

A good challenge.

**Comment by 65001** [comment]
Atleast for the custom functions you can use it to implement functions left of SQLITE by default sure as Regex & Median.
From looking at StackOverflow I found some code that would bind a sample Regex function to a connection. I just haven't figured out how to add a custom function by a method or like
