### ISSUE TITLE
Adding new API's to LitDev

### ISSUE THREAD

**Issue by 65001** [litdev1/LitDev#21]
I am in the process of writing an API client for https://restcountries.eu/ so that LitDev could have a basic geography API. I will submit a pull request as soon as I finish up unit testing.

What are your thoughts on including https://www.metaweather.com/api/ to replace the Google's weather API? The geoid stuff from the website seems to be a bit hit and miss on locating smaller cities and rural areas.

I was looking at https://financialmodelingprep.com/developer/docs and was wondering if you would think that adding functionality to get stock prices and currency exchange rates would fit in well with the rest of the library?

**Comment by litdev1** [comment]
Hi,  Theses are all good ideas.
The only issue I have found with web APIs is they sometimes are withdrawn or become not free or otherwise suddenly stop working so should be tested for every so often - the test stuff you got me to add would be ideal for these type methods that can stop working due to external reasons.
For example you see a depreciated LDWeather that had this issue

**Comment by litdev1** [comment]
PS when you do a pull request, it would be great if you only do the C# and any test files, not project or solution files which may be VS version dependent.

**Comment by litdev1** [comment]
Merged, Thanks

**Comment by 65001** [comment]
I would ensure the descriptions for Geography meet your standards before putting it in the stable release.

**Comment by litdev1** [comment]
I write intellisense comments for summary, all parameters (describing options and allowed values) and possible return values, e.g. stating "FAILED" is returned on failure.  I would like to cover all these, since it helps the user.

Sometimes a very short example in the intellisense.

If the methods are more complex, then I will include a Small Basic code example in the download.
If you want to do the intellisense and maybe a small sample file.

**Comment by 65001** [comment]
The intellisense is the stuff in between the `<summary>` blocks right? Are the samples on github, so I can do a pull request to them?

**Comment by litdev1** [comment]
Yes, summay param retruns etc.  These are auto used to create xml, intellisense documentation etc.

If you write the method, then before adding any summary blocks, type /// before the method it will set up all the required blocks.

e.g.

        /// <summary>
        /// 
        /// </summary>
        /// <param name="code"></param>
        /// <returns></returns>
        public static Primitive GetCountriesByCode(Primitive code)

Then fill the blocks in.

The samples are not on github, perhaps they should be, I will add them I think

**Comment by litdev1** [comment]
Samples added

**Comment by litdev1** [comment]
When writing summary etc, remember it is for SB users, not C# experts so I would say for example:

Returns an array ...
Not
Returns a Primitive array ...

SB users probably have no idea what Primitive is.

For something like "Primitive callingCode", I might give a simple example value that would work, eg 7 is the value for Russian Federation. so they could try the method with the sample parameter value without guessing what it might mean.
Also I might describe the array if it has complex tructure like data[1]["name"] - this is 2D arrays, what are the 2 dimensions, what special index values are there e.g. "name".  If describing the input or output fairly fully gets too complicated, then perhaps consider if it is too complex - sometimes with SB we simplify a bit to be useful to beginners rather than give every last bit of possible functionality - its a judgement call

**Comment by litdev1** [comment]
Just playing with the geography - realy cool once I see how much data it has - nice job.
A good little sample will be useful.
