### ISSUE TITLE
Clarification on Query vs Command for SQLITE

### ISSUE THREAD

**Issue by 65001** [litdev1/LitDev#6]
Hello LitDev

I issued the code shown [here](http://kripken.github.io/sql.js/GUI/) and executed it as a query and the insert statements seem to ran for sqlite. When I attempted to run it as a command just the query's were ignored. 

Is this the intended behavior of the two or did I misunderstand or do something wrong with my code and the like.

Thanks in advance

**Comment by litdev1** [comment]
Not exactly by design but appears to be the way it is - not something I particulary tried to achieve.

Command certaily doesn't do queries.  

But since the query is also filling a datatable with results I think it captures commands as well.  I use a SQLite version of [this command](https://msdn.microsoft.com/en-us/library/905keexk(v=vs.110).aspx).

**Comment by 65001** [comment]
Thanks for the clarification, does any of the other databases fall into the antipattern?

**Comment by litdev1** [comment]
Without testing each one I would think so since [the code](https://github.com/litdev1/LitDev/blob/master/LitDev/LitDev/DataBase.cs) for each is virtually identical, just using different parent classes.

**Comment by 65001** [comment]
Okay thanks, time to redo some button captions & the like. Thank you.
